### ISSUE TITLE
Using this plugin to create cacheable vendor chunk

### ISSUE THREAD

**Issue by skleeschulte** [szrenwei/inline-manifest-webpack-plugin#1]
Hi @szrenwei, I saw that you [proposed to use this plugin](https://github.com/ampedandwired/html-webpack-plugin/issues/143#issuecomment-220229751) instead of [chunk-manifest-webpack-plugin](https://github.com/diurnalist/chunk-manifest-webpack-plugin) to make a [vendor chunk](https://webpack.github.io/docs/list-of-plugins.html#2-explicit-vendor-chunk) cacheable. Can you explain how that works?

**Comment by szrenwei** [comment]
@skleeschulte 
The CommonsChunkPlugin can separate the runtime code into manifest.js; thus the vendor chunk won't change any more when you change other chunks, instead, the manifest.js change.

``` javascript
[
    new webpack.optimize.CommonsChunkPlugin({
        names: ['common', 'manifest']
    })
]
```

Since manifest.js changes frequently, so it's better to inline it in your html's script tag to save http request. Inline the manifest.js is boring, so let's the plugin to do the dirty thing. This plugin need to use with HtmlWebpackPlugin, it just does a simple thing, exact the manifest.js source code, put it into `htmlWebpackPlugin` and then out put it in your html.

**Comment by skleeschulte** [comment]
Ok, but what about using an explicit vendor chunk with its own entry point [like described in the webpack docs](https://webpack.github.io/docs/list-of-plugins.html#2-explicit-vendor-chunk)? The setup is like this:

```
entry: {
  vendor: ["jquery", "other-lib"],
  app: "./entry"
}
new CommonsChunkPlugin({
  name: "vendor",
  minChunks: Infinity
})
```

and

```
<script src="vendor.js" charset="utf-8"></script>
<script src="app.js" charset="utf-8"></script>
```

Here you can declare explicitly what should go into the vendor chunk. With your configuration (`{ names: ['common', 'manifest'] }`) and just an app entry point, as I understand it nothing would go into the `common` chunk (or am I wrong?). And even if there were multiple entry points, only the common modules referenced in both entry points would go into the `common` chunk, but not, say, `react` and `redux` if they are referenced only in one of the entry points. At least that's how I understand [the docs](https://webpack.github.io/docs/list-of-plugins.html#1-commons-chunk-for-entries).

In addition, can you explain how generating manifest.js works and how to make sure that the webpack runtime is always in manifest.js?

**Comment by szrenwei** [comment]
@skleeschulte as far as I know, explicit vendor chunk can't solve the problem, the runtime code will generally goes into the first entry chunk, so every time the runtime code change, your vendor code will change. So no matter you use `common` or `vendor`, you need explicit separate the `manifest` out. Use the following configue:

``` javascript
entry: {
  vendor: ["jquery", "other-lib"],
  app: "./entry"
}
new CommonsChunkPlugin({
  names: ["vendor", "manifest"],
  minChunks: Infinity
})
```

this will make sure the runtime code goes into `manifest.js`, if your like to inline this small script, just use my plugin.
