### ISSUE TITLE
目前是不是不暴漏到变量了？

### ISSUE THREAD

**Issue by sanonz** [szrenwei/inline-manifest-webpack-plugin#18]
因为我需要自定义 `HtmlWebpackPlugin` 模版的结构，所以把 `inject: false` 关闭了，以前是通过 `<%= htmlWebpackPlugin.files.webpackManifest %>` 引用代码，请问现在怎么引用？

**Comment by szrenwei** [comment]
@sanonz 

现在加上了，升级到 4.0.2，然后使用：
```javascript
<%= htmlWebpackPlugin.files.runtime %>
````
