### ISSUE TITLE
Provide documentation for using inline-manifest-webpack-plugin

### ISSUE THREAD

**Issue by Hamada14** [szrenwei/inline-manifest-webpack-plugin#19]
Would it be possible to add a working example for using inline-manifest-webpack-plugin with [manifest-plugin](https://www.npmjs.com/package/webpack-manifest-plugin)?

Also It'd be great to add some document to how does inline-manifest-webpack-plugin work to encourage contribution to the project and allow people to understand how it's working to ease using the plugin.

**Comment by szrenwei** [comment]
You can view the source code of `react-dev-utils`(https://github.com/facebook/create-react-app/blob/master/packages/react-dev-utils/InlineChunkHtmlPlugin.js) , it does the same thing, and much simpler.
