### ISSUE TITLE
Manifest injected in the opening html tag when setting inject to true in the HtmlWebpackPlugin settings

### ISSUE THREAD

**Issue by michael-wolfenden** [szrenwei/inline-manifest-webpack-plugin#3]
When setting inject to true in the `HtmlWebpackPlugin` settings, the manifest source is injected into the opening html tag.

The reason is that the `manifest` asset is used by the `HtmlWebpackPlugin` for a different purpose. See the specific code below
https://github.com/ampedandwired/html-webpack-plugin/blob/390635a5197921d54d15ecb5247d26c523cb6886/index.js#L511

Is it possible to use a different asset name or make the asset name configurable?

**Comment by szrenwei** [comment]
@michael-wolfenden thanks for feedback, I have solved this issue, you can use v2.0.0 and config the name now.
