### ISSUE TITLE
Automatically inject manifest

### ISSUE THREAD

**Issue by insin** [szrenwei/inline-manifest-webpack-plugin#5]
Would it be possible to add functionality to this plugin to have it automatically inject the manifest `<script>` tag into the HTML being generated?

I just wrote this plugin to inject it in my build, but it would be cool if something similar could be rolled into this plugin:

``` js
/**
 * Inject a <script> tag containing the Webpack manifest prior to HtmlPlugin
 * injecting tags for generated assets.
 */
function injectManifest() {
  this.plugin('compilation', (compilation) => {
    compilation.plugin('html-webpack-plugin-before-html-processing', (htmlPluginData, cb) => {
      let {assets, html} = htmlPluginData
      htmlPluginData.html = html.replace('</body>', `${assets.webpackManifest}</body>`)
      cb()
    })
  })
}
```

**Comment by rohitlodha** [comment]
@insin  Is there any working example of where to write this code in webpack.config?

**Comment by bogusfocused** [comment]
I have tried to implement based on this plugin and your idea here https://github.com/rohitlodha/html-webpack-inline-chunk-plugin

**Comment by szrenwei** [comment]
updated!!! please use the v4 of this plugin, sorry for update so late..
