### ISSUE TITLE
manifest.js file is created anyway

### ISSUE THREAD

**Issue by oluckyman** [szrenwei/inline-manifest-webpack-plugin#6]
I set up the plugin, it injects the manifest into html as expected. It also removes

```
<script type="text/javascript" src="/manifest.js"></script>
```

from index.html, but the file itself is remains in build dir.

Why is it important for me is that I’m getting this error:

```
Cannot use [chunkhash] for chunk in '[name].[chunkhash].js' (use [hash] instead)
```

on manifest.js file.
So I thought that if I’ll inline manifest into html, webpack will not try to apply `[name].[chunkname].js` pattern to the manifest.

Here is my config:

```
var config = {
  entry: {
    app: [
      '/app.js'
    ],
    vendor: getVendors()
  },

  output: {
    path: path.join(__dirname, '/build/'),
    sourcePrefix: '\t',
    publicPath: '/',
    filename: '[name].js',
    // filename: '[name].[chunkhash].js',
  },

  plugins: [
    new webpack.optimize.CommonsChunkPlugin({
      names: ['vendor', 'manifest']
    }),
    new InlineManifestWebpackPlugin({
      name: 'webpackManifest'
    }),
  ]
};
```

**Comment by oluckyman** [comment]
ok, I’ve managed to fix my issue with chunk hash by updating the config this way:

```
var config = {
  output: {
    // filename: '[name].js',
    filename: '[name].[chunkhash].js',
  },

  plugins: [
    // new webpack.optimize.CommonsChunkPlugin({
    //   names: ['vendor', 'manifest']
    // }),
    new webpack.optimize.CommonsChunkPlugin({
      name: 'vendor'
    }),
    new webpack.optimize.CommonsChunkPlugin({
      name: 'manifest',
      filename: 'manifest.js',
      minChunks: Infinity,
    }),
  ]
};
```

now it creates 'app' and 'vendor' files with chunkhash and 'manifest.js' without hash. So it’s not deal-breaker anymore. But still, `manifest.js` in output dir is not needed

**Comment by herecydev** [comment]
Also seeing this, the manifest is still produced after being inlined into the html.

**Comment by cdflove9426** [comment]
if you ues  ` new webpack.HotModuleReplacementPlugin()`  , delete it at  product env。

**Comment by szrenwei** [comment]
updated!!! please use the v4 of this plugin, sorry for update so late..
